# /etc/netplan/99-config.yaml

network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: true
    enp0s8:
      addresses:
        - 172.16.94.12/24
      routes:
        - to: default
          via: 172.16.94.1
      nameservers:
        addresses: [8.8.4.4,8.8.8.8]